### ISSUE TITLE
Desaturation Controller

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#100]
- [x] Understand the power budget & decide on how much power could be allocated to the MTQs during nominal operating modes (everything in ConOps except CLPM and LPM).
    - Resource: [EPS ICD Section 9](https://docs.google.com/document/d/1RWSsyaqM_lcErxgnjZGZMGTRuZLiQLasIb6quAjUcKg/edit#)
    
- [x] Understand the control law for magnetic desaturation and put together a library for the desat controller. 
    - [x] Develop a simple unit test of the library 
    - [x] Integrate the library with the main flight software
    - [x] Demonstrate that the correct behaviour is happening in FSW by showing that momentum does not accumulate in the wheels (basically, do a nonlinear/full-sim version of your unit test)
    - Build off of the existing library, *but save the current version*. 
    - Resource: TBD

- [x] Analyze MTQ power consumption during desaturation. Understand and quantify the balance between momentum coming in due to disturbances and momentum being "removed" by the MTQs.
   - [x] Some simple analysis exists in `Test/Analysis/DesatSSO`, make sure you understand this (& sanity check)
   - [x] Build a more complete test, effectively by creating a version of the test with a real magnetic field, your controller, real disturbance models, etc. (This maybe could just be done in the main sim...your call, once we get there)
   - [x] The output I care about here is the *minimum maximum dipole* that we can set (in software) such that the wheel momentum does not increase on average over one orbit. Key question: does this dipole result in a balanced power budget? (is there enough power for MTQs to counteract the resulting dipole continuously?)

**Comment by Nick-Melville** [comment]
This is completed. Note that given that our orbit will have a local ascending node time of 1800, we should have plenty of power for the MTQs.
