### ISSUE TITLE
Sensor Model Updates

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#114]
To match the processing module, the magnetometer and gyroscope models need to be updated so that:

- [x] The outputs are in the correct sensor frame, as dictated by their datasheets and orientation on the OB1 board
    - Contact: Ryan Lorette for sensor orientations. 
- [x] The noise model is consistent with any calibrations being done by the processing module. For example, if an affine calibration model is being used in FSW, then the original reading should be distorted by the inverse operation. 

- [x] Once updates are done, provide two unit tests that show
    - [x] Magnetometer: track from a true magnetic field reading `B_eci_T`, through the sensor model & FSW processing, with output `B_meas_body_T`. Using a known quaternion, show that the error between `B_eci_T` and `B_meas_eci_T` is consistently small.
    - [x] Gyroscope: track from a true angular velocity `w_body_radps`, through the sensor model & FSW processing, with output `w_meas_body_radps`. Show that the error between the two signals is consistently small. 

- [x] Merge the sensor processing libraries into FSW. Run a simulation with these changes and show that things look the same as before changes were made.
    - Note: you will not need to do anything for the sensor models, because the sim already references the library files. Simply updating the libraries will be sufficient to have changes propagate into the sim.

**Comment by tpreynolds** [comment]
This is complete, although some of the numbers for frame transformation/calibration constants appear to be placeholders.

**Comment by Nick-Melville** [comment]
This is complete.
