### ISSUE TITLE
Merge EPS Module Into Sim

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#119]
I've started a branch called `dev_eps` for us to port over the EPS simulation into flight software.

**Code Organization**
I'll create a folder called `Lib/EPS` where we can store all of the EPS-specific libraries. 

**Porting Your Code**
I'll create an empty library using the same structure as the rest of the sim that you can port your code into. (This will live in the folder above.) If you need any additional inputs, please send me a slack message. If you want to know a little bit more about how the libraries work, I've got a short description [on the wiki.](https://github.com/AA-CubeSat-Team/soci-gnc/wiki)

Please use the init file too for all of your parameters. A template is located in the `Lib/EPS` folder, and has the inputs/outputs that you'll need. There's a description of how this is meant to work in the same wiki linked above.

**Before You Can Run The Sim**
I need to do some surgery on the payload. Currently it is only buildable on *nix systems. So you won't be able to "run" the sim out of the box because the payload is in there & needs to be built. If you are on a *nix system, then you can build the payload by running `build_soar.m` from within the `Lib/FSW/soar/build` folder, as long as you have a MEX compiler.

**Comment by Nick-Melville** [comment]
A version of the power model is in the main_sim now. It could be improved in many ways but I think it is sufficient for now.
