### ISSUE TITLE
Desaturation controller

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#28]
Implement the method that we talked about to steer the wheel momentum to a desired value using the following pseudocode:
`if (dh==0)`
    `    exit`
`else`
    `torque = -k Alloc( dh )`
   ` if (torque == 0)`
        `torque = -k h^w_B`

**Comment by c0lem3** [comment]
I believe this problem is solved now. I can't find a situation where it fails anymore
