### ISSUE TITLE
Rate Transition Between FSW and Sensors

### ISSUE THREAD

**Issue by devantormey** [AA-CubeSat-Team/soci-gnc#31]
Simulink defaults the current rate to the upstream condition. Therefore because there is no rate transition in FSW it defaults to the Sensor block Rate transition. This can cause issues for operation within FSW. We should (at some point) at rate transitions at the enterance to FSW.

**Comment by tpreynolds** [comment]
All sensors are being run at the sim sample rate right now. Fine for development. Transition to FSW rate is being handled.
