### ISSUE TITLE
Qualifying Initial Guess of Quaternion Convergence and accrued Eclipse Propagation Error

### ISSUE THREAD

**Issue by kashton6** [AA-CubeSat-Team/soci-gnc#32]
So I am currently working on code to show if and when an inital guess converges to the correct quaternion. I am sweeping through initial quaternion errors from 180 deg all the way down to 0 deg and seeing how things converge (settling time), all for given initial angular velocity magnitudes.  This is a file called Quat_initial_guess in soci-gnc\Test\Estimation_test\Unit Testing\Full Function Unit Test. You 

secondly, I will make plots showing the error growth of the quaternion estimation during eclipse mode (propagation step only)

**Comment by tpreynolds** [comment]
Make sure you're testing different directions too.A reasonably clean way to do that could be to keep the EKF initial guess constant, and vary the initial condition of the sim (the "truth" value).  I would write a little function that uniformly samples from the quaternion sphere to define the initial conditions of the sim.
