### ISSUE TITLE
Folder restructuring

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#4]
Organize the folders in a new branch and then do a pull request to merge it into dev. Change the names on all libraries/functions to reflect our discussion and put the convention you're using in the top-level ReadMe.

**Comment by tpreynolds** [comment]
@devantormey Some comments on the renaming:

- Move all unit tests out of the `Utilities_Tools` folder
- The `Quat` folder in lib/Dynamics should not be there -- just use the matlab libraries for these, no need to reinvent the wheel.
- The controller libraries do not go in dynamics. These should be moved somewhere like `lib/fsw/attitude_control`
- The names in Environment are inconsistent. Each of the three sub-folders have issues. 
    - Make sure the suffix "lib" is always spelled the same (lowercase).
- Clean up the `Time_Coordinates/Time` folder. There are too many .slx files in there that (i) don't follow the naming convention and (ii) it isn't clear what they actually do.
- The names in `Test/Environment` aren't consistent with `Lib/Environment`. 
    - same with `Test/Time_Coordinates` and `Lib/Time_Coordinates`.

**Comment by tpreynolds** [comment]
Also time/coordinate rotations are environment things, they should maybe live in the environment folder .. your call

**Comment by devantormey** [comment]
Notes to me:
- There are still parameters in Sim_init --> pick a way to split initial conditions and controller 1 stuff
- ask Ivan about the last stray time library "time2rotation"
- move time_coordinates into environment? maybe?
