### ISSUE TITLE
Cleaning up leftover variables

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#50]
Just to avoid having to write `clear var1 var2 .... varN` over and over at the end of the init files, let's change them each to `clearvars -except fswParams simParams TLE` 

Feel free to add whatever other variables are needed here. Still feels like these should be functions, since we're replicating that "scoped" behaviour with a script, but it's fine if we're too far along (or if it's too annoying) to make that change right now.

**Comment by c0lem3** [comment]
I agree. should we be adding #%codegen to files as well?

**Comment by tpreynolds** [comment]
Yep, every Matlab function inside FSW should have that. It'll make simulink throw an error a build time if there's something done incorrectly that won't autocode
