### ISSUE TITLE
Triad Activation

### ISSUE THREAD

**Issue by tpreynolds** [AA-CubeSat-Team/soci-gnc#74]
- set the `Triad_Activate` signal to have an initial condition of 1
  - this will come in as a telecommand from ground/CDH
  - the rate transition should set the initial condition properly, but we may want/need to use a unit delay instead
  - keep the existing check for gyro validity as is

**Comment by kashton6** [comment]
Update: The triad activation library is completed and can be found in attitude estimation in flight software. Check ICD for explanation, the initial condition for Triad activation is 1 and will activate triad on the next available time step when measurements are available. 

For the future, we still need better protection against parallel sun/mag measurements. This will include feeding in vectors to the triad that are closer and closer together, and finding the threshold at which the the triad become inaccurate. When this threshold is met, the measurements should be rotated slightly so they are farther apart such that the triad can calculate, with a little error, a quaternion.

**Comment by tpreynolds** [comment]
As part of pull req #82 I've added the TRIAD_activate signal to the incoming signal from CDH, and fed it forward to the MEKF library.

**Comment by tpreynolds** [comment]
TRIAD unit tested & the activation looks good. Just need to do the analysis to set the threshold in some meaningful way.

**Comment by tpreynolds** [comment]
Carried out the error analysis. 

Method: using a random DCM and a random primary (unit) vector, calculate the secondary vector by rotating the primary by a smaller and smaller angle about the same axis. Check the TRIAD error as a function of the angle difference between the primary and secondary vectors. Image attached. Based on the results, I've set the parallel threshold as 1e-5 degrees, this should mean that TRIAD produces maximum errors of < 0.1 degrees to the absolute truth, solely due to numerical error. This 0.1 deg is irrespective of any measurement noise that will increase TRIAD errors.

Code: unit test can be found in `Test/FSW/Attitude_estimation/triad_estimator_test(_init)`  

![triad_error](https://user-images.githubusercontent.com/29679775/104067452-31c5e680-51d1-11eb-98ef-c45b87905067.png)
