### ISSUE TITLE
Sensor voting scheme needs to be finished/integrated into FSW

### ISSUE THREAD

**Issue by kashton6** [AA-CubeSat-Team/soci-gnc#79]
So as we have 3 magnetometers and 3 gyros for redundancy, We have to be able to choose which sensor measurements of the three get past through to the estimation block. Devan had been working on this and I think he said it was done or close to being done:  

I can only find this file: Lib/FSW/voting_scheme/voting_scheme_lib.slx found on dev branch. 
I wrote the sun sensor 2x1 radian to a 3x1 degree conversion block within that library. The blocks inside that need replacement are the variable selector blocks. 

Devan wrote a matlab code that does it found here: Test/Estimation_test/Voting_test.m  on the dev_dev branch. I think all that needs to happen is transpose it into simulink, if it hasn't been done already. If no one wants to tackle finishing this, I can look into it, or at least explain a bit more. Let me know.

**Comment by kashton6** [comment]
Update, Davan told me that the library was never finished, so this is a simulink library that needs to be completed, not just located somewhere on github.

**Comment by tpreynolds** [comment]
The current start can be found in `Lib/FSW/sensor_processing/voting_scheme`

**Comment by tpreynolds** [comment]
This task is complete, unit tests exist. Corresponding changes need to be made to sensor libraries before anything can be merged. Tracking those sensor model updates in a separate issue.
